// Code generated by hertz generator.

package main

import (
	"admin/biz/infras/logger"
	"admin/biz/mw"
	"admin/conf"
	"admin/rpc"
	"common/consts"
	"common/mtl"
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	prometheus "github.com/hertz-contrib/monitor-prometheus"
	"github.com/hertz-contrib/obs-opentelemetry/tracing"

	"net/http"

	"github.com/hertz-contrib/opensergo/sentinel/adapter"
	"github.com/hertz-contrib/pprof"
)

func Init() {
	mtl.InitFlightRecorder()
	rpc.InitRpc()
	mw.InitJwt()
	logger.InitLog(true)
	mtl.InitProvider(consts.AdminServiceName)
}

var serviceAddress = conf.GetConf().Hertz.Address
var serviceTracer = conf.GetConf().Hertz.Tracer

func main() {

	Init()

	//info := serversuite.GetInfo("admin", "9010", 1)
	tracer, cfg := tracing.NewServerTracer()
	h := server.New(
		server.WithStreamBody(true),
		server.WithHostPorts(serviceAddress),
		server.WithHandleMethodNotAllowed(true),
		//server.WithRegistry(r, info),
		tracer,
		server.WithTracer(
			prometheus.NewServerTracer(serviceTracer, "/hertz",
				prometheus.WithEnableGoCollector(true), // enable go runtime metric collector
			),
		),
	)
	//h.NoHijackConnPool = true
	//文件导出
	h.Static("/export", "./files/")

	// use pprof mw
	pprof.Register(h)
	// use otel mw
	h.Use(tracing.ServerMiddleware(cfg))

	h.Use(adapter.SentinelServerMiddleware(
		// abort with status 429 by default
		adapter.WithServerBlockFallback(func(c context.Context, ctx *app.RequestContext) {
			ctx.JSON(http.StatusTooManyRequests, nil)
			ctx.Abort()
		}),
	))

	register(h)

	h.Spin()
}
