### Send POST request with json body
POST http://127.0.0.1:9010/service/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456",
  "captcha": "123456"
}

### GET request with a header
GET https://examples.http-client.intellij.net/ip
Authorization: Basic YWRtaW46MTIzNDU2
Accept: application/json


### Send POST request with json body
POST http://127.0.0.1:9010/service/dict/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjgyMDYwNjIsImlkIjp7ImlkIjoxfSwib3JpZ19pYXQiOjE3NjgyMDI0NjJ9.DUBRMvDUVWO20OVXq5rtV3QnA_3DrlDXxczV3iwMwJE


### Send POST request with json body
POST http://127.0.0.1:9010/service/logs/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjYwNDg4OTMsImlkIjp7ImlkIjoxfSwib3JpZ19pYXQiOjE3NjYwNDUyOTN9.SF1C2cZNvmqHi7SZhw9M9jBzf0cUiDQrlMWPmaphtSI


### Send POST request with json body
POST http://127.0.0.1:9010/service/item/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjYwNDg4OTMsImlkIjp7ImlkIjoxfSwib3JpZ19pYXQiOjE3NjYwNDUyOTN9.SF1C2cZNvmqHi7SZhw9M9jBzf0cUiDQrlMWPmaphtSI