### Send POST request with json body
POST http://127.0.0.1:9089/service/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456",
  "captcha": "123456"
}

### GET request with a header
GET https://examples.http-client.intellij.net/ip
Authorization: Basic YWRtaW46MTIzNDU2
Accept: application/json
