// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"user/biz/dal/db/ent/predicate"
	"user/biz/dal/db/ent/userloginrestriction"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserLoginRestrictionDelete is the builder for deleting a UserLoginRestriction entity.
type UserLoginRestrictionDelete struct {
	config
	hooks    []Hook
	mutation *UserLoginRestrictionMutation
}

// Where appends a list predicates to the UserLoginRestrictionDelete builder.
func (_d *UserLoginRestrictionDelete) Where(ps ...predicate.UserLoginRestriction) *UserLoginRestrictionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserLoginRestrictionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserLoginRestrictionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserLoginRestrictionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userloginrestriction.Table, sqlgraph.NewFieldSpec(userloginrestriction.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserLoginRestrictionDeleteOne is the builder for deleting a single UserLoginRestriction entity.
type UserLoginRestrictionDeleteOne struct {
	_d *UserLoginRestrictionDelete
}

// Where appends a list predicates to the UserLoginRestrictionDelete builder.
func (_d *UserLoginRestrictionDeleteOne) Where(ps ...predicate.UserLoginRestriction) *UserLoginRestrictionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserLoginRestrictionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userloginrestriction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserLoginRestrictionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
