// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "primary key"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "created time"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "last update time"},
		{Name: "delete", Type: field.TypeInt64, Nullable: true, Comment: "last delete  1:已删除 0:未删除", Default: 0},
		{Name: "created_id", Type: field.TypeInt64, Nullable: true, Comment: "created", Default: 0},
		{Name: "status", Type: field.TypeInt64, Nullable: true, Comment: "状态[0:禁用;1:正常]", Default: 1},
		{Name: "name", Type: field.TypeString, Nullable: true, Comment: "名称"},
		{Name: "code", Type: field.TypeString, Nullable: true, Comment: "标识"},
		{Name: "pic", Type: field.TypeString, Nullable: true, Comment: "主图", Default: ""},
		{Name: "desc", Type: field.TypeString, Nullable: true, Comment: "概述", Default: ""},
		{Name: "type", Type: field.TypeString, Nullable: true, Comment: "类型"},
		{Name: "duration", Type: field.TypeInt64, Nullable: true, Comment: "总时长"},
		{Name: "length", Type: field.TypeInt64, Nullable: true, Comment: "单次时长"},
		{Name: "count", Type: field.TypeInt64, Nullable: true, Comment: "次数"},
		{Name: "price", Type: field.TypeInt64, Nullable: true, Comment: "定价"},
		{Name: "tag_id", Type: field.TypeJSON, Nullable: true, Comment: "标签"},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:       "items",
		Columns:    ItemsColumns,
		PrimaryKey: []*schema.Column{ItemsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "item_id",
				Unique:  false,
				Columns: []*schema.Column{ItemsColumns[0]},
			},
			{
				Name:    "item_name_code",
				Unique:  false,
				Columns: []*schema.Column{ItemsColumns[6], ItemsColumns[7]},
			},
		},
	}
	// ProductColumns holds the columns for the "product" table.
	ProductColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "primary key"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "created time"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "last update time"},
		{Name: "delete", Type: field.TypeInt64, Nullable: true, Comment: "last delete  1:已删除 0:未删除", Default: 0},
		{Name: "created_id", Type: field.TypeInt64, Nullable: true, Comment: "created", Default: 0},
		{Name: "status", Type: field.TypeInt64, Nullable: true, Comment: "状态[0:禁用;1:正常]", Default: 1},
		{Name: "name", Type: field.TypeString, Nullable: true, Comment: "商品名"},
		{Name: "code", Type: field.TypeString, Nullable: true, Comment: "标识"},
		{Name: "pic", Type: field.TypeString, Nullable: true, Comment: "主图"},
		{Name: "desc", Type: field.TypeString, Nullable: true, Comment: "详情"},
		{Name: "price", Type: field.TypeInt64, Nullable: true, Comment: "价格"},
		{Name: "stock", Type: field.TypeInt64, Nullable: true, Comment: "库存"},
		{Name: "is_sales", Type: field.TypeJSON, Nullable: true, Comment: "销售方式 1会员端 2PC端"},
		{Name: "sign_sales_at", Type: field.TypeTime, Nullable: true, Comment: "开始售卖时间"},
		{Name: "end_sales_at", Type: field.TypeTime, Nullable: true, Comment: "结束售卖时间"},
	}
	// ProductTable holds the schema information for the "product" table.
	ProductTable = &schema.Table{
		Name:       "product",
		Columns:    ProductColumns,
		PrimaryKey: []*schema.Column{ProductColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "product_id",
				Unique:  false,
				Columns: []*schema.Column{ProductColumns[0]},
			},
		},
	}
	// ProductItemsColumns holds the columns for the "product_items" table.
	ProductItemsColumns = []*schema.Column{
		{Name: "product_id", Type: field.TypeInt64},
		{Name: "item_id", Type: field.TypeInt64},
	}
	// ProductItemsTable holds the schema information for the "product_items" table.
	ProductItemsTable = &schema.Table{
		Name:       "product_items",
		Columns:    ProductItemsColumns,
		PrimaryKey: []*schema.Column{ProductItemsColumns[0], ProductItemsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "product_items_product_id",
				Columns:    []*schema.Column{ProductItemsColumns[0]},
				RefColumns: []*schema.Column{ProductColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "product_items_item_id",
				Columns:    []*schema.Column{ProductItemsColumns[1]},
				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ItemsTable,
		ProductTable,
		ProductItemsTable,
	}
)

func init() {
	ItemsTable.Annotation = &entsql.Annotation{
		Table: "items",
	}
	ProductTable.Annotation = &entsql.Annotation{
		Table: "product",
	}
	ProductItemsTable.ForeignKeys[0].RefTable = ProductTable
	ProductItemsTable.ForeignKeys[1].RefTable = ItemsTable
}
