// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hardware/biz/dal/db/ent/hardware"
	"hardware/biz/dal/db/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HardwareUpdate is the builder for updating Hardware entities.
type HardwareUpdate struct {
	config
	hooks    []Hook
	mutation *HardwareMutation
}

// Where appends a list predicates to the HardwareUpdate builder.
func (_u *HardwareUpdate) Where(ps ...predicate.Hardware) *HardwareUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HardwareUpdate) SetUpdatedAt(v time.Time) *HardwareUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *HardwareUpdate) ClearUpdatedAt() *HardwareUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDelete sets the "delete" field.
func (_u *HardwareUpdate) SetDelete(v int64) *HardwareUpdate {
	_u.mutation.ResetDelete()
	_u.mutation.SetDelete(v)
	return _u
}

// SetNillableDelete sets the "delete" field if the given value is not nil.
func (_u *HardwareUpdate) SetNillableDelete(v *int64) *HardwareUpdate {
	if v != nil {
		_u.SetDelete(*v)
	}
	return _u
}

// AddDelete adds value to the "delete" field.
func (_u *HardwareUpdate) AddDelete(v int64) *HardwareUpdate {
	_u.mutation.AddDelete(v)
	return _u
}

// ClearDelete clears the value of the "delete" field.
func (_u *HardwareUpdate) ClearDelete() *HardwareUpdate {
	_u.mutation.ClearDelete()
	return _u
}

// SetCreatedID sets the "created_id" field.
func (_u *HardwareUpdate) SetCreatedID(v int64) *HardwareUpdate {
	_u.mutation.ResetCreatedID()
	_u.mutation.SetCreatedID(v)
	return _u
}

// SetNillableCreatedID sets the "created_id" field if the given value is not nil.
func (_u *HardwareUpdate) SetNillableCreatedID(v *int64) *HardwareUpdate {
	if v != nil {
		_u.SetCreatedID(*v)
	}
	return _u
}

// AddCreatedID adds value to the "created_id" field.
func (_u *HardwareUpdate) AddCreatedID(v int64) *HardwareUpdate {
	_u.mutation.AddCreatedID(v)
	return _u
}

// ClearCreatedID clears the value of the "created_id" field.
func (_u *HardwareUpdate) ClearCreatedID() *HardwareUpdate {
	_u.mutation.ClearCreatedID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *HardwareUpdate) SetStatus(v int64) *HardwareUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *HardwareUpdate) SetNillableStatus(v *int64) *HardwareUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *HardwareUpdate) AddStatus(v int64) *HardwareUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *HardwareUpdate) ClearStatus() *HardwareUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetName sets the "name" field.
func (_u *HardwareUpdate) SetName(v string) *HardwareUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HardwareUpdate) SetNillableName(v *string) *HardwareUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *HardwareUpdate) ClearName() *HardwareUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetPic sets the "pic" field.
func (_u *HardwareUpdate) SetPic(v string) *HardwareUpdate {
	_u.mutation.SetPic(v)
	return _u
}

// SetNillablePic sets the "pic" field if the given value is not nil.
func (_u *HardwareUpdate) SetNillablePic(v *string) *HardwareUpdate {
	if v != nil {
		_u.SetPic(*v)
	}
	return _u
}

// ClearPic clears the value of the "pic" field.
func (_u *HardwareUpdate) ClearPic() *HardwareUpdate {
	_u.mutation.ClearPic()
	return _u
}

// Mutation returns the HardwareMutation object of the builder.
func (_u *HardwareUpdate) Mutation() *HardwareMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HardwareUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HardwareUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HardwareUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HardwareUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HardwareUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := hardware.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *HardwareUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(hardware.Table, hardware.Columns, sqlgraph.NewFieldSpec(hardware.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(hardware.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(hardware.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(hardware.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Delete(); ok {
		_spec.SetField(hardware.FieldDelete, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDelete(); ok {
		_spec.AddField(hardware.FieldDelete, field.TypeInt64, value)
	}
	if _u.mutation.DeleteCleared() {
		_spec.ClearField(hardware.FieldDelete, field.TypeInt64)
	}
	if value, ok := _u.mutation.CreatedID(); ok {
		_spec.SetField(hardware.FieldCreatedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedID(); ok {
		_spec.AddField(hardware.FieldCreatedID, field.TypeInt64, value)
	}
	if _u.mutation.CreatedIDCleared() {
		_spec.ClearField(hardware.FieldCreatedID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(hardware.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(hardware.FieldStatus, field.TypeInt64, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(hardware.FieldStatus, field.TypeInt64)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(hardware.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(hardware.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Pic(); ok {
		_spec.SetField(hardware.FieldPic, field.TypeString, value)
	}
	if _u.mutation.PicCleared() {
		_spec.ClearField(hardware.FieldPic, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hardware.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HardwareUpdateOne is the builder for updating a single Hardware entity.
type HardwareUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HardwareMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *HardwareUpdateOne) SetUpdatedAt(v time.Time) *HardwareUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *HardwareUpdateOne) ClearUpdatedAt() *HardwareUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDelete sets the "delete" field.
func (_u *HardwareUpdateOne) SetDelete(v int64) *HardwareUpdateOne {
	_u.mutation.ResetDelete()
	_u.mutation.SetDelete(v)
	return _u
}

// SetNillableDelete sets the "delete" field if the given value is not nil.
func (_u *HardwareUpdateOne) SetNillableDelete(v *int64) *HardwareUpdateOne {
	if v != nil {
		_u.SetDelete(*v)
	}
	return _u
}

// AddDelete adds value to the "delete" field.
func (_u *HardwareUpdateOne) AddDelete(v int64) *HardwareUpdateOne {
	_u.mutation.AddDelete(v)
	return _u
}

// ClearDelete clears the value of the "delete" field.
func (_u *HardwareUpdateOne) ClearDelete() *HardwareUpdateOne {
	_u.mutation.ClearDelete()
	return _u
}

// SetCreatedID sets the "created_id" field.
func (_u *HardwareUpdateOne) SetCreatedID(v int64) *HardwareUpdateOne {
	_u.mutation.ResetCreatedID()
	_u.mutation.SetCreatedID(v)
	return _u
}

// SetNillableCreatedID sets the "created_id" field if the given value is not nil.
func (_u *HardwareUpdateOne) SetNillableCreatedID(v *int64) *HardwareUpdateOne {
	if v != nil {
		_u.SetCreatedID(*v)
	}
	return _u
}

// AddCreatedID adds value to the "created_id" field.
func (_u *HardwareUpdateOne) AddCreatedID(v int64) *HardwareUpdateOne {
	_u.mutation.AddCreatedID(v)
	return _u
}

// ClearCreatedID clears the value of the "created_id" field.
func (_u *HardwareUpdateOne) ClearCreatedID() *HardwareUpdateOne {
	_u.mutation.ClearCreatedID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *HardwareUpdateOne) SetStatus(v int64) *HardwareUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *HardwareUpdateOne) SetNillableStatus(v *int64) *HardwareUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *HardwareUpdateOne) AddStatus(v int64) *HardwareUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *HardwareUpdateOne) ClearStatus() *HardwareUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetName sets the "name" field.
func (_u *HardwareUpdateOne) SetName(v string) *HardwareUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HardwareUpdateOne) SetNillableName(v *string) *HardwareUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *HardwareUpdateOne) ClearName() *HardwareUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetPic sets the "pic" field.
func (_u *HardwareUpdateOne) SetPic(v string) *HardwareUpdateOne {
	_u.mutation.SetPic(v)
	return _u
}

// SetNillablePic sets the "pic" field if the given value is not nil.
func (_u *HardwareUpdateOne) SetNillablePic(v *string) *HardwareUpdateOne {
	if v != nil {
		_u.SetPic(*v)
	}
	return _u
}

// ClearPic clears the value of the "pic" field.
func (_u *HardwareUpdateOne) ClearPic() *HardwareUpdateOne {
	_u.mutation.ClearPic()
	return _u
}

// Mutation returns the HardwareMutation object of the builder.
func (_u *HardwareUpdateOne) Mutation() *HardwareMutation {
	return _u.mutation
}

// Where appends a list predicates to the HardwareUpdate builder.
func (_u *HardwareUpdateOne) Where(ps ...predicate.Hardware) *HardwareUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HardwareUpdateOne) Select(field string, fields ...string) *HardwareUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Hardware entity.
func (_u *HardwareUpdateOne) Save(ctx context.Context) (*Hardware, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HardwareUpdateOne) SaveX(ctx context.Context) *Hardware {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HardwareUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HardwareUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *HardwareUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := hardware.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *HardwareUpdateOne) sqlSave(ctx context.Context) (_node *Hardware, err error) {
	_spec := sqlgraph.NewUpdateSpec(hardware.Table, hardware.Columns, sqlgraph.NewFieldSpec(hardware.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Hardware.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hardware.FieldID)
		for _, f := range fields {
			if !hardware.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hardware.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(hardware.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(hardware.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(hardware.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Delete(); ok {
		_spec.SetField(hardware.FieldDelete, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDelete(); ok {
		_spec.AddField(hardware.FieldDelete, field.TypeInt64, value)
	}
	if _u.mutation.DeleteCleared() {
		_spec.ClearField(hardware.FieldDelete, field.TypeInt64)
	}
	if value, ok := _u.mutation.CreatedID(); ok {
		_spec.SetField(hardware.FieldCreatedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedID(); ok {
		_spec.AddField(hardware.FieldCreatedID, field.TypeInt64, value)
	}
	if _u.mutation.CreatedIDCleared() {
		_spec.ClearField(hardware.FieldCreatedID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(hardware.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(hardware.FieldStatus, field.TypeInt64, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(hardware.FieldStatus, field.TypeInt64)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(hardware.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(hardware.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Pic(); ok {
		_spec.SetField(hardware.FieldPic, field.TypeString, value)
	}
	if _u.mutation.PicCleared() {
		_spec.ClearField(hardware.FieldPic, field.TypeString)
	}
	_node = &Hardware{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hardware.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
