// Code generated by ent, DO NOT EDIT.

package ent

import (
	"hardware/biz/dal/db/ent/hardware"
	"hardware/biz/dal/db/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	hardwareMixin := schema.Hardware{}.Mixin()
	hardwareMixinFields0 := hardwareMixin[0].Fields()
	_ = hardwareMixinFields0
	hardwareMixinFields1 := hardwareMixin[1].Fields()
	_ = hardwareMixinFields1
	hardwareFields := schema.Hardware{}.Fields()
	_ = hardwareFields
	// hardwareDescCreatedAt is the schema descriptor for created_at field.
	hardwareDescCreatedAt := hardwareMixinFields0[1].Descriptor()
	// hardware.DefaultCreatedAt holds the default value on creation for the created_at field.
	hardware.DefaultCreatedAt = hardwareDescCreatedAt.Default.(func() time.Time)
	// hardwareDescUpdatedAt is the schema descriptor for updated_at field.
	hardwareDescUpdatedAt := hardwareMixinFields0[2].Descriptor()
	// hardware.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	hardware.DefaultUpdatedAt = hardwareDescUpdatedAt.Default.(func() time.Time)
	// hardware.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	hardware.UpdateDefaultUpdatedAt = hardwareDescUpdatedAt.UpdateDefault.(func() time.Time)
	// hardwareDescDelete is the schema descriptor for delete field.
	hardwareDescDelete := hardwareMixinFields0[3].Descriptor()
	// hardware.DefaultDelete holds the default value on creation for the delete field.
	hardware.DefaultDelete = hardwareDescDelete.Default.(int64)
	// hardwareDescCreatedID is the schema descriptor for created_id field.
	hardwareDescCreatedID := hardwareMixinFields0[4].Descriptor()
	// hardware.DefaultCreatedID holds the default value on creation for the created_id field.
	hardware.DefaultCreatedID = hardwareDescCreatedID.Default.(int64)
	// hardwareDescStatus is the schema descriptor for status field.
	hardwareDescStatus := hardwareMixinFields1[0].Descriptor()
	// hardware.DefaultStatus holds the default value on creation for the status field.
	hardware.DefaultStatus = hardwareDescStatus.Default.(int64)
	// hardwareDescPic is the schema descriptor for pic field.
	hardwareDescPic := hardwareFields[1].Descriptor()
	// hardware.DefaultPic holds the default value on creation for the pic field.
	hardware.DefaultPic = hardwareDescPic.Default.(string)
}
