// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"deer/biz/dal/db/mysql/ent/order"
	"deer/biz/dal/db/mysql/ent/orderevents"
	"deer/biz/infras/common"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderEventsCreate is the builder for creating a OrderEvents entity.
type OrderEventsCreate struct {
	config
	mutation *OrderEventsMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrderEventsCreate) SetCreatedAt(v time.Time) *OrderEventsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrderEventsCreate) SetNillableCreatedAt(v *time.Time) *OrderEventsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrderEventsCreate) SetUpdatedAt(v time.Time) *OrderEventsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrderEventsCreate) SetNillableUpdatedAt(v *time.Time) *OrderEventsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDelete sets the "delete" field.
func (_c *OrderEventsCreate) SetDelete(v int64) *OrderEventsCreate {
	_c.mutation.SetDelete(v)
	return _c
}

// SetNillableDelete sets the "delete" field if the given value is not nil.
func (_c *OrderEventsCreate) SetNillableDelete(v *int64) *OrderEventsCreate {
	if v != nil {
		_c.SetDelete(*v)
	}
	return _c
}

// SetCreatedID sets the "created_id" field.
func (_c *OrderEventsCreate) SetCreatedID(v int64) *OrderEventsCreate {
	_c.mutation.SetCreatedID(v)
	return _c
}

// SetNillableCreatedID sets the "created_id" field if the given value is not nil.
func (_c *OrderEventsCreate) SetNillableCreatedID(v *int64) *OrderEventsCreate {
	if v != nil {
		_c.SetCreatedID(*v)
	}
	return _c
}

// SetEventID sets the "event_id" field.
func (_c *OrderEventsCreate) SetEventID(v string) *OrderEventsCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetNillableEventID sets the "event_id" field if the given value is not nil.
func (_c *OrderEventsCreate) SetNillableEventID(v *string) *OrderEventsCreate {
	if v != nil {
		_c.SetEventID(*v)
	}
	return _c
}

// SetAggregateID sets the "aggregate_id" field.
func (_c *OrderEventsCreate) SetAggregateID(v int64) *OrderEventsCreate {
	_c.mutation.SetAggregateID(v)
	return _c
}

// SetNillableAggregateID sets the "aggregate_id" field if the given value is not nil.
func (_c *OrderEventsCreate) SetNillableAggregateID(v *int64) *OrderEventsCreate {
	if v != nil {
		_c.SetAggregateID(*v)
	}
	return _c
}

// SetAggregateType sets the "aggregate_type" field.
func (_c *OrderEventsCreate) SetAggregateType(v string) *OrderEventsCreate {
	_c.mutation.SetAggregateType(v)
	return _c
}

// SetNillableAggregateType sets the "aggregate_type" field if the given value is not nil.
func (_c *OrderEventsCreate) SetNillableAggregateType(v *string) *OrderEventsCreate {
	if v != nil {
		_c.SetAggregateType(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *OrderEventsCreate) SetEventType(v string) *OrderEventsCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_c *OrderEventsCreate) SetNillableEventType(v *string) *OrderEventsCreate {
	if v != nil {
		_c.SetEventType(*v)
	}
	return _c
}

// SetEventData sets the "event_data" field.
func (_c *OrderEventsCreate) SetEventData(v *common.EventData) *OrderEventsCreate {
	_c.mutation.SetEventData(v)
	return _c
}

// SetEventVersion sets the "event_version" field.
func (_c *OrderEventsCreate) SetEventVersion(v int64) *OrderEventsCreate {
	_c.mutation.SetEventVersion(v)
	return _c
}

// SetNillableEventVersion sets the "event_version" field if the given value is not nil.
func (_c *OrderEventsCreate) SetNillableEventVersion(v *int64) *OrderEventsCreate {
	if v != nil {
		_c.SetEventVersion(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OrderEventsCreate) SetID(v int64) *OrderEventsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (_c *OrderEventsCreate) SetOrderID(id int64) *OrderEventsCreate {
	_c.mutation.SetOrderID(id)
	return _c
}

// SetNillableOrderID sets the "order" edge to the Order entity by ID if the given value is not nil.
func (_c *OrderEventsCreate) SetNillableOrderID(id *int64) *OrderEventsCreate {
	if id != nil {
		_c = _c.SetOrderID(*id)
	}
	return _c
}

// SetOrder sets the "order" edge to the Order entity.
func (_c *OrderEventsCreate) SetOrder(v *Order) *OrderEventsCreate {
	return _c.SetOrderID(v.ID)
}

// Mutation returns the OrderEventsMutation object of the builder.
func (_c *OrderEventsCreate) Mutation() *OrderEventsMutation {
	return _c.mutation
}

// Save creates the OrderEvents in the database.
func (_c *OrderEventsCreate) Save(ctx context.Context) (*OrderEvents, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrderEventsCreate) SaveX(ctx context.Context) *OrderEvents {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderEventsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderEventsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrderEventsCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := orderevents.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := orderevents.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Delete(); !ok {
		v := orderevents.DefaultDelete
		_c.mutation.SetDelete(v)
	}
	if _, ok := _c.mutation.CreatedID(); !ok {
		v := orderevents.DefaultCreatedID
		_c.mutation.SetCreatedID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrderEventsCreate) check() error {
	return nil
}

func (_c *OrderEventsCreate) sqlSave(ctx context.Context) (*OrderEvents, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrderEventsCreate) createSpec() (*OrderEvents, *sqlgraph.CreateSpec) {
	var (
		_node = &OrderEvents{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(orderevents.Table, sqlgraph.NewFieldSpec(orderevents.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(orderevents.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(orderevents.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Delete(); ok {
		_spec.SetField(orderevents.FieldDelete, field.TypeInt64, value)
		_node.Delete = value
	}
	if value, ok := _c.mutation.CreatedID(); ok {
		_spec.SetField(orderevents.FieldCreatedID, field.TypeInt64, value)
		_node.CreatedID = value
	}
	if value, ok := _c.mutation.EventID(); ok {
		_spec.SetField(orderevents.FieldEventID, field.TypeString, value)
		_node.EventID = value
	}
	if value, ok := _c.mutation.AggregateType(); ok {
		_spec.SetField(orderevents.FieldAggregateType, field.TypeString, value)
		_node.AggregateType = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(orderevents.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.EventData(); ok {
		_spec.SetField(orderevents.FieldEventData, field.TypeJSON, value)
		_node.EventData = value
	}
	if value, ok := _c.mutation.EventVersion(); ok {
		_spec.SetField(orderevents.FieldEventVersion, field.TypeInt64, value)
		_node.EventVersion = value
	}
	if nodes := _c.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderevents.OrderTable,
			Columns: []string{orderevents.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AggregateID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrderEvents.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrderEventsUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrderEventsCreate) OnConflict(opts ...sql.ConflictOption) *OrderEventsUpsertOne {
	_c.conflict = opts
	return &OrderEventsUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrderEvents.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrderEventsCreate) OnConflictColumns(columns ...string) *OrderEventsUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrderEventsUpsertOne{
		create: _c,
	}
}

type (
	// OrderEventsUpsertOne is the builder for "upsert"-ing
	//  one OrderEvents node.
	OrderEventsUpsertOne struct {
		create *OrderEventsCreate
	}

	// OrderEventsUpsert is the "OnConflict" setter.
	OrderEventsUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderEventsUpsert) SetUpdatedAt(v time.Time) *OrderEventsUpsert {
	u.Set(orderevents.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderEventsUpsert) UpdateUpdatedAt() *OrderEventsUpsert {
	u.SetExcluded(orderevents.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *OrderEventsUpsert) ClearUpdatedAt() *OrderEventsUpsert {
	u.SetNull(orderevents.FieldUpdatedAt)
	return u
}

// SetDelete sets the "delete" field.
func (u *OrderEventsUpsert) SetDelete(v int64) *OrderEventsUpsert {
	u.Set(orderevents.FieldDelete, v)
	return u
}

// UpdateDelete sets the "delete" field to the value that was provided on create.
func (u *OrderEventsUpsert) UpdateDelete() *OrderEventsUpsert {
	u.SetExcluded(orderevents.FieldDelete)
	return u
}

// AddDelete adds v to the "delete" field.
func (u *OrderEventsUpsert) AddDelete(v int64) *OrderEventsUpsert {
	u.Add(orderevents.FieldDelete, v)
	return u
}

// ClearDelete clears the value of the "delete" field.
func (u *OrderEventsUpsert) ClearDelete() *OrderEventsUpsert {
	u.SetNull(orderevents.FieldDelete)
	return u
}

// SetCreatedID sets the "created_id" field.
func (u *OrderEventsUpsert) SetCreatedID(v int64) *OrderEventsUpsert {
	u.Set(orderevents.FieldCreatedID, v)
	return u
}

// UpdateCreatedID sets the "created_id" field to the value that was provided on create.
func (u *OrderEventsUpsert) UpdateCreatedID() *OrderEventsUpsert {
	u.SetExcluded(orderevents.FieldCreatedID)
	return u
}

// AddCreatedID adds v to the "created_id" field.
func (u *OrderEventsUpsert) AddCreatedID(v int64) *OrderEventsUpsert {
	u.Add(orderevents.FieldCreatedID, v)
	return u
}

// ClearCreatedID clears the value of the "created_id" field.
func (u *OrderEventsUpsert) ClearCreatedID() *OrderEventsUpsert {
	u.SetNull(orderevents.FieldCreatedID)
	return u
}

// SetEventID sets the "event_id" field.
func (u *OrderEventsUpsert) SetEventID(v string) *OrderEventsUpsert {
	u.Set(orderevents.FieldEventID, v)
	return u
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *OrderEventsUpsert) UpdateEventID() *OrderEventsUpsert {
	u.SetExcluded(orderevents.FieldEventID)
	return u
}

// ClearEventID clears the value of the "event_id" field.
func (u *OrderEventsUpsert) ClearEventID() *OrderEventsUpsert {
	u.SetNull(orderevents.FieldEventID)
	return u
}

// SetAggregateID sets the "aggregate_id" field.
func (u *OrderEventsUpsert) SetAggregateID(v int64) *OrderEventsUpsert {
	u.Set(orderevents.FieldAggregateID, v)
	return u
}

// UpdateAggregateID sets the "aggregate_id" field to the value that was provided on create.
func (u *OrderEventsUpsert) UpdateAggregateID() *OrderEventsUpsert {
	u.SetExcluded(orderevents.FieldAggregateID)
	return u
}

// ClearAggregateID clears the value of the "aggregate_id" field.
func (u *OrderEventsUpsert) ClearAggregateID() *OrderEventsUpsert {
	u.SetNull(orderevents.FieldAggregateID)
	return u
}

// SetAggregateType sets the "aggregate_type" field.
func (u *OrderEventsUpsert) SetAggregateType(v string) *OrderEventsUpsert {
	u.Set(orderevents.FieldAggregateType, v)
	return u
}

// UpdateAggregateType sets the "aggregate_type" field to the value that was provided on create.
func (u *OrderEventsUpsert) UpdateAggregateType() *OrderEventsUpsert {
	u.SetExcluded(orderevents.FieldAggregateType)
	return u
}

// ClearAggregateType clears the value of the "aggregate_type" field.
func (u *OrderEventsUpsert) ClearAggregateType() *OrderEventsUpsert {
	u.SetNull(orderevents.FieldAggregateType)
	return u
}

// SetEventType sets the "event_type" field.
func (u *OrderEventsUpsert) SetEventType(v string) *OrderEventsUpsert {
	u.Set(orderevents.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *OrderEventsUpsert) UpdateEventType() *OrderEventsUpsert {
	u.SetExcluded(orderevents.FieldEventType)
	return u
}

// ClearEventType clears the value of the "event_type" field.
func (u *OrderEventsUpsert) ClearEventType() *OrderEventsUpsert {
	u.SetNull(orderevents.FieldEventType)
	return u
}

// SetEventData sets the "event_data" field.
func (u *OrderEventsUpsert) SetEventData(v *common.EventData) *OrderEventsUpsert {
	u.Set(orderevents.FieldEventData, v)
	return u
}

// UpdateEventData sets the "event_data" field to the value that was provided on create.
func (u *OrderEventsUpsert) UpdateEventData() *OrderEventsUpsert {
	u.SetExcluded(orderevents.FieldEventData)
	return u
}

// ClearEventData clears the value of the "event_data" field.
func (u *OrderEventsUpsert) ClearEventData() *OrderEventsUpsert {
	u.SetNull(orderevents.FieldEventData)
	return u
}

// SetEventVersion sets the "event_version" field.
func (u *OrderEventsUpsert) SetEventVersion(v int64) *OrderEventsUpsert {
	u.Set(orderevents.FieldEventVersion, v)
	return u
}

// UpdateEventVersion sets the "event_version" field to the value that was provided on create.
func (u *OrderEventsUpsert) UpdateEventVersion() *OrderEventsUpsert {
	u.SetExcluded(orderevents.FieldEventVersion)
	return u
}

// AddEventVersion adds v to the "event_version" field.
func (u *OrderEventsUpsert) AddEventVersion(v int64) *OrderEventsUpsert {
	u.Add(orderevents.FieldEventVersion, v)
	return u
}

// ClearEventVersion clears the value of the "event_version" field.
func (u *OrderEventsUpsert) ClearEventVersion() *OrderEventsUpsert {
	u.SetNull(orderevents.FieldEventVersion)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OrderEvents.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(orderevents.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OrderEventsUpsertOne) UpdateNewValues() *OrderEventsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(orderevents.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(orderevents.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrderEvents.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrderEventsUpsertOne) Ignore() *OrderEventsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrderEventsUpsertOne) DoNothing() *OrderEventsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrderEventsCreate.OnConflict
// documentation for more info.
func (u *OrderEventsUpsertOne) Update(set func(*OrderEventsUpsert)) *OrderEventsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrderEventsUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderEventsUpsertOne) SetUpdatedAt(v time.Time) *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderEventsUpsertOne) UpdateUpdatedAt() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *OrderEventsUpsertOne) ClearUpdatedAt() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDelete sets the "delete" field.
func (u *OrderEventsUpsertOne) SetDelete(v int64) *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetDelete(v)
	})
}

// AddDelete adds v to the "delete" field.
func (u *OrderEventsUpsertOne) AddDelete(v int64) *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.AddDelete(v)
	})
}

// UpdateDelete sets the "delete" field to the value that was provided on create.
func (u *OrderEventsUpsertOne) UpdateDelete() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateDelete()
	})
}

// ClearDelete clears the value of the "delete" field.
func (u *OrderEventsUpsertOne) ClearDelete() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearDelete()
	})
}

// SetCreatedID sets the "created_id" field.
func (u *OrderEventsUpsertOne) SetCreatedID(v int64) *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetCreatedID(v)
	})
}

// AddCreatedID adds v to the "created_id" field.
func (u *OrderEventsUpsertOne) AddCreatedID(v int64) *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.AddCreatedID(v)
	})
}

// UpdateCreatedID sets the "created_id" field to the value that was provided on create.
func (u *OrderEventsUpsertOne) UpdateCreatedID() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateCreatedID()
	})
}

// ClearCreatedID clears the value of the "created_id" field.
func (u *OrderEventsUpsertOne) ClearCreatedID() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearCreatedID()
	})
}

// SetEventID sets the "event_id" field.
func (u *OrderEventsUpsertOne) SetEventID(v string) *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetEventID(v)
	})
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *OrderEventsUpsertOne) UpdateEventID() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateEventID()
	})
}

// ClearEventID clears the value of the "event_id" field.
func (u *OrderEventsUpsertOne) ClearEventID() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearEventID()
	})
}

// SetAggregateID sets the "aggregate_id" field.
func (u *OrderEventsUpsertOne) SetAggregateID(v int64) *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetAggregateID(v)
	})
}

// UpdateAggregateID sets the "aggregate_id" field to the value that was provided on create.
func (u *OrderEventsUpsertOne) UpdateAggregateID() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateAggregateID()
	})
}

// ClearAggregateID clears the value of the "aggregate_id" field.
func (u *OrderEventsUpsertOne) ClearAggregateID() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearAggregateID()
	})
}

// SetAggregateType sets the "aggregate_type" field.
func (u *OrderEventsUpsertOne) SetAggregateType(v string) *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetAggregateType(v)
	})
}

// UpdateAggregateType sets the "aggregate_type" field to the value that was provided on create.
func (u *OrderEventsUpsertOne) UpdateAggregateType() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateAggregateType()
	})
}

// ClearAggregateType clears the value of the "aggregate_type" field.
func (u *OrderEventsUpsertOne) ClearAggregateType() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearAggregateType()
	})
}

// SetEventType sets the "event_type" field.
func (u *OrderEventsUpsertOne) SetEventType(v string) *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *OrderEventsUpsertOne) UpdateEventType() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateEventType()
	})
}

// ClearEventType clears the value of the "event_type" field.
func (u *OrderEventsUpsertOne) ClearEventType() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearEventType()
	})
}

// SetEventData sets the "event_data" field.
func (u *OrderEventsUpsertOne) SetEventData(v *common.EventData) *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetEventData(v)
	})
}

// UpdateEventData sets the "event_data" field to the value that was provided on create.
func (u *OrderEventsUpsertOne) UpdateEventData() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateEventData()
	})
}

// ClearEventData clears the value of the "event_data" field.
func (u *OrderEventsUpsertOne) ClearEventData() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearEventData()
	})
}

// SetEventVersion sets the "event_version" field.
func (u *OrderEventsUpsertOne) SetEventVersion(v int64) *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetEventVersion(v)
	})
}

// AddEventVersion adds v to the "event_version" field.
func (u *OrderEventsUpsertOne) AddEventVersion(v int64) *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.AddEventVersion(v)
	})
}

// UpdateEventVersion sets the "event_version" field to the value that was provided on create.
func (u *OrderEventsUpsertOne) UpdateEventVersion() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateEventVersion()
	})
}

// ClearEventVersion clears the value of the "event_version" field.
func (u *OrderEventsUpsertOne) ClearEventVersion() *OrderEventsUpsertOne {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearEventVersion()
	})
}

// Exec executes the query.
func (u *OrderEventsUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrderEventsCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrderEventsUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrderEventsUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrderEventsUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrderEventsCreateBulk is the builder for creating many OrderEvents entities in bulk.
type OrderEventsCreateBulk struct {
	config
	err      error
	builders []*OrderEventsCreate
	conflict []sql.ConflictOption
}

// Save creates the OrderEvents entities in the database.
func (_c *OrderEventsCreateBulk) Save(ctx context.Context) ([]*OrderEvents, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrderEvents, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderEventsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrderEventsCreateBulk) SaveX(ctx context.Context) []*OrderEvents {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderEventsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderEventsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrderEvents.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrderEventsUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrderEventsCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrderEventsUpsertBulk {
	_c.conflict = opts
	return &OrderEventsUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrderEvents.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrderEventsCreateBulk) OnConflictColumns(columns ...string) *OrderEventsUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrderEventsUpsertBulk{
		create: _c,
	}
}

// OrderEventsUpsertBulk is the builder for "upsert"-ing
// a bulk of OrderEvents nodes.
type OrderEventsUpsertBulk struct {
	create *OrderEventsCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OrderEvents.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(orderevents.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OrderEventsUpsertBulk) UpdateNewValues() *OrderEventsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(orderevents.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(orderevents.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrderEvents.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrderEventsUpsertBulk) Ignore() *OrderEventsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrderEventsUpsertBulk) DoNothing() *OrderEventsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrderEventsCreateBulk.OnConflict
// documentation for more info.
func (u *OrderEventsUpsertBulk) Update(set func(*OrderEventsUpsert)) *OrderEventsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrderEventsUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderEventsUpsertBulk) SetUpdatedAt(v time.Time) *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderEventsUpsertBulk) UpdateUpdatedAt() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *OrderEventsUpsertBulk) ClearUpdatedAt() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDelete sets the "delete" field.
func (u *OrderEventsUpsertBulk) SetDelete(v int64) *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetDelete(v)
	})
}

// AddDelete adds v to the "delete" field.
func (u *OrderEventsUpsertBulk) AddDelete(v int64) *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.AddDelete(v)
	})
}

// UpdateDelete sets the "delete" field to the value that was provided on create.
func (u *OrderEventsUpsertBulk) UpdateDelete() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateDelete()
	})
}

// ClearDelete clears the value of the "delete" field.
func (u *OrderEventsUpsertBulk) ClearDelete() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearDelete()
	})
}

// SetCreatedID sets the "created_id" field.
func (u *OrderEventsUpsertBulk) SetCreatedID(v int64) *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetCreatedID(v)
	})
}

// AddCreatedID adds v to the "created_id" field.
func (u *OrderEventsUpsertBulk) AddCreatedID(v int64) *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.AddCreatedID(v)
	})
}

// UpdateCreatedID sets the "created_id" field to the value that was provided on create.
func (u *OrderEventsUpsertBulk) UpdateCreatedID() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateCreatedID()
	})
}

// ClearCreatedID clears the value of the "created_id" field.
func (u *OrderEventsUpsertBulk) ClearCreatedID() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearCreatedID()
	})
}

// SetEventID sets the "event_id" field.
func (u *OrderEventsUpsertBulk) SetEventID(v string) *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetEventID(v)
	})
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *OrderEventsUpsertBulk) UpdateEventID() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateEventID()
	})
}

// ClearEventID clears the value of the "event_id" field.
func (u *OrderEventsUpsertBulk) ClearEventID() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearEventID()
	})
}

// SetAggregateID sets the "aggregate_id" field.
func (u *OrderEventsUpsertBulk) SetAggregateID(v int64) *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetAggregateID(v)
	})
}

// UpdateAggregateID sets the "aggregate_id" field to the value that was provided on create.
func (u *OrderEventsUpsertBulk) UpdateAggregateID() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateAggregateID()
	})
}

// ClearAggregateID clears the value of the "aggregate_id" field.
func (u *OrderEventsUpsertBulk) ClearAggregateID() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearAggregateID()
	})
}

// SetAggregateType sets the "aggregate_type" field.
func (u *OrderEventsUpsertBulk) SetAggregateType(v string) *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetAggregateType(v)
	})
}

// UpdateAggregateType sets the "aggregate_type" field to the value that was provided on create.
func (u *OrderEventsUpsertBulk) UpdateAggregateType() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateAggregateType()
	})
}

// ClearAggregateType clears the value of the "aggregate_type" field.
func (u *OrderEventsUpsertBulk) ClearAggregateType() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearAggregateType()
	})
}

// SetEventType sets the "event_type" field.
func (u *OrderEventsUpsertBulk) SetEventType(v string) *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *OrderEventsUpsertBulk) UpdateEventType() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateEventType()
	})
}

// ClearEventType clears the value of the "event_type" field.
func (u *OrderEventsUpsertBulk) ClearEventType() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearEventType()
	})
}

// SetEventData sets the "event_data" field.
func (u *OrderEventsUpsertBulk) SetEventData(v *common.EventData) *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetEventData(v)
	})
}

// UpdateEventData sets the "event_data" field to the value that was provided on create.
func (u *OrderEventsUpsertBulk) UpdateEventData() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateEventData()
	})
}

// ClearEventData clears the value of the "event_data" field.
func (u *OrderEventsUpsertBulk) ClearEventData() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearEventData()
	})
}

// SetEventVersion sets the "event_version" field.
func (u *OrderEventsUpsertBulk) SetEventVersion(v int64) *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.SetEventVersion(v)
	})
}

// AddEventVersion adds v to the "event_version" field.
func (u *OrderEventsUpsertBulk) AddEventVersion(v int64) *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.AddEventVersion(v)
	})
}

// UpdateEventVersion sets the "event_version" field to the value that was provided on create.
func (u *OrderEventsUpsertBulk) UpdateEventVersion() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.UpdateEventVersion()
	})
}

// ClearEventVersion clears the value of the "event_version" field.
func (u *OrderEventsUpsertBulk) ClearEventVersion() *OrderEventsUpsertBulk {
	return u.Update(func(s *OrderEventsUpsert) {
		s.ClearEventVersion()
	})
}

// Exec executes the query.
func (u *OrderEventsUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrderEventsCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrderEventsCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrderEventsUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
