// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kcers-order/biz/dal/db/mysql/ent/ordereventsubscriptions"
	"kcers-order/biz/dal/db/mysql/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderEventSubscriptionsQuery is the builder for querying OrderEventSubscriptions entities.
type OrderEventSubscriptionsQuery struct {
	config
	ctx        *QueryContext
	order      []ordereventsubscriptions.OrderOption
	inters     []Interceptor
	predicates []predicate.OrderEventSubscriptions
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrderEventSubscriptionsQuery builder.
func (oesq *OrderEventSubscriptionsQuery) Where(ps ...predicate.OrderEventSubscriptions) *OrderEventSubscriptionsQuery {
	oesq.predicates = append(oesq.predicates, ps...)
	return oesq
}

// Limit the number of records to be returned by this query.
func (oesq *OrderEventSubscriptionsQuery) Limit(limit int) *OrderEventSubscriptionsQuery {
	oesq.ctx.Limit = &limit
	return oesq
}

// Offset to start from.
func (oesq *OrderEventSubscriptionsQuery) Offset(offset int) *OrderEventSubscriptionsQuery {
	oesq.ctx.Offset = &offset
	return oesq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (oesq *OrderEventSubscriptionsQuery) Unique(unique bool) *OrderEventSubscriptionsQuery {
	oesq.ctx.Unique = &unique
	return oesq
}

// Order specifies how the records should be ordered.
func (oesq *OrderEventSubscriptionsQuery) Order(o ...ordereventsubscriptions.OrderOption) *OrderEventSubscriptionsQuery {
	oesq.order = append(oesq.order, o...)
	return oesq
}

// First returns the first OrderEventSubscriptions entity from the query.
// Returns a *NotFoundError when no OrderEventSubscriptions was found.
func (oesq *OrderEventSubscriptionsQuery) First(ctx context.Context) (*OrderEventSubscriptions, error) {
	nodes, err := oesq.Limit(1).All(setContextOp(ctx, oesq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ordereventsubscriptions.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (oesq *OrderEventSubscriptionsQuery) FirstX(ctx context.Context) *OrderEventSubscriptions {
	node, err := oesq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrderEventSubscriptions ID from the query.
// Returns a *NotFoundError when no OrderEventSubscriptions ID was found.
func (oesq *OrderEventSubscriptionsQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = oesq.Limit(1).IDs(setContextOp(ctx, oesq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ordereventsubscriptions.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (oesq *OrderEventSubscriptionsQuery) FirstIDX(ctx context.Context) int64 {
	id, err := oesq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrderEventSubscriptions entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OrderEventSubscriptions entity is found.
// Returns a *NotFoundError when no OrderEventSubscriptions entities are found.
func (oesq *OrderEventSubscriptionsQuery) Only(ctx context.Context) (*OrderEventSubscriptions, error) {
	nodes, err := oesq.Limit(2).All(setContextOp(ctx, oesq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ordereventsubscriptions.Label}
	default:
		return nil, &NotSingularError{ordereventsubscriptions.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (oesq *OrderEventSubscriptionsQuery) OnlyX(ctx context.Context) *OrderEventSubscriptions {
	node, err := oesq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrderEventSubscriptions ID in the query.
// Returns a *NotSingularError when more than one OrderEventSubscriptions ID is found.
// Returns a *NotFoundError when no entities are found.
func (oesq *OrderEventSubscriptionsQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = oesq.Limit(2).IDs(setContextOp(ctx, oesq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ordereventsubscriptions.Label}
	default:
		err = &NotSingularError{ordereventsubscriptions.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (oesq *OrderEventSubscriptionsQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := oesq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrderEventSubscriptionsSlice.
func (oesq *OrderEventSubscriptionsQuery) All(ctx context.Context) ([]*OrderEventSubscriptions, error) {
	ctx = setContextOp(ctx, oesq.ctx, ent.OpQueryAll)
	if err := oesq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OrderEventSubscriptions, *OrderEventSubscriptionsQuery]()
	return withInterceptors[[]*OrderEventSubscriptions](ctx, oesq, qr, oesq.inters)
}

// AllX is like All, but panics if an error occurs.
func (oesq *OrderEventSubscriptionsQuery) AllX(ctx context.Context) []*OrderEventSubscriptions {
	nodes, err := oesq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrderEventSubscriptions IDs.
func (oesq *OrderEventSubscriptionsQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if oesq.ctx.Unique == nil && oesq.path != nil {
		oesq.Unique(true)
	}
	ctx = setContextOp(ctx, oesq.ctx, ent.OpQueryIDs)
	if err = oesq.Select(ordereventsubscriptions.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (oesq *OrderEventSubscriptionsQuery) IDsX(ctx context.Context) []int64 {
	ids, err := oesq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (oesq *OrderEventSubscriptionsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, oesq.ctx, ent.OpQueryCount)
	if err := oesq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, oesq, querierCount[*OrderEventSubscriptionsQuery](), oesq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (oesq *OrderEventSubscriptionsQuery) CountX(ctx context.Context) int {
	count, err := oesq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (oesq *OrderEventSubscriptionsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, oesq.ctx, ent.OpQueryExist)
	switch _, err := oesq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (oesq *OrderEventSubscriptionsQuery) ExistX(ctx context.Context) bool {
	exist, err := oesq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrderEventSubscriptionsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (oesq *OrderEventSubscriptionsQuery) Clone() *OrderEventSubscriptionsQuery {
	if oesq == nil {
		return nil
	}
	return &OrderEventSubscriptionsQuery{
		config:     oesq.config,
		ctx:        oesq.ctx.Clone(),
		order:      append([]ordereventsubscriptions.OrderOption{}, oesq.order...),
		inters:     append([]Interceptor{}, oesq.inters...),
		predicates: append([]predicate.OrderEventSubscriptions{}, oesq.predicates...),
		// clone intermediate query.
		sql:  oesq.sql.Clone(),
		path: oesq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrderEventSubscriptions.Query().
//		GroupBy(ordereventsubscriptions.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (oesq *OrderEventSubscriptionsQuery) GroupBy(field string, fields ...string) *OrderEventSubscriptionsGroupBy {
	oesq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OrderEventSubscriptionsGroupBy{build: oesq}
	grbuild.flds = &oesq.ctx.Fields
	grbuild.label = ordereventsubscriptions.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.OrderEventSubscriptions.Query().
//		Select(ordereventsubscriptions.FieldCreatedAt).
//		Scan(ctx, &v)
func (oesq *OrderEventSubscriptionsQuery) Select(fields ...string) *OrderEventSubscriptionsSelect {
	oesq.ctx.Fields = append(oesq.ctx.Fields, fields...)
	sbuild := &OrderEventSubscriptionsSelect{OrderEventSubscriptionsQuery: oesq}
	sbuild.label = ordereventsubscriptions.Label
	sbuild.flds, sbuild.scan = &oesq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OrderEventSubscriptionsSelect configured with the given aggregations.
func (oesq *OrderEventSubscriptionsQuery) Aggregate(fns ...AggregateFunc) *OrderEventSubscriptionsSelect {
	return oesq.Select().Aggregate(fns...)
}

func (oesq *OrderEventSubscriptionsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range oesq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, oesq); err != nil {
				return err
			}
		}
	}
	for _, f := range oesq.ctx.Fields {
		if !ordereventsubscriptions.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if oesq.path != nil {
		prev, err := oesq.path(ctx)
		if err != nil {
			return err
		}
		oesq.sql = prev
	}
	return nil
}

func (oesq *OrderEventSubscriptionsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OrderEventSubscriptions, error) {
	var (
		nodes = []*OrderEventSubscriptions{}
		_spec = oesq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OrderEventSubscriptions).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OrderEventSubscriptions{config: oesq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, oesq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (oesq *OrderEventSubscriptionsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := oesq.querySpec()
	_spec.Node.Columns = oesq.ctx.Fields
	if len(oesq.ctx.Fields) > 0 {
		_spec.Unique = oesq.ctx.Unique != nil && *oesq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, oesq.driver, _spec)
}

func (oesq *OrderEventSubscriptionsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ordereventsubscriptions.Table, ordereventsubscriptions.Columns, sqlgraph.NewFieldSpec(ordereventsubscriptions.FieldID, field.TypeInt64))
	_spec.From = oesq.sql
	if unique := oesq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if oesq.path != nil {
		_spec.Unique = true
	}
	if fields := oesq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ordereventsubscriptions.FieldID)
		for i := range fields {
			if fields[i] != ordereventsubscriptions.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := oesq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := oesq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := oesq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := oesq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (oesq *OrderEventSubscriptionsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(oesq.driver.Dialect())
	t1 := builder.Table(ordereventsubscriptions.Table)
	columns := oesq.ctx.Fields
	if len(columns) == 0 {
		columns = ordereventsubscriptions.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if oesq.sql != nil {
		selector = oesq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if oesq.ctx.Unique != nil && *oesq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range oesq.predicates {
		p(selector)
	}
	for _, p := range oesq.order {
		p(selector)
	}
	if offset := oesq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := oesq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OrderEventSubscriptionsGroupBy is the group-by builder for OrderEventSubscriptions entities.
type OrderEventSubscriptionsGroupBy struct {
	selector
	build *OrderEventSubscriptionsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (oesgb *OrderEventSubscriptionsGroupBy) Aggregate(fns ...AggregateFunc) *OrderEventSubscriptionsGroupBy {
	oesgb.fns = append(oesgb.fns, fns...)
	return oesgb
}

// Scan applies the selector query and scans the result into the given value.
func (oesgb *OrderEventSubscriptionsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oesgb.build.ctx, ent.OpQueryGroupBy)
	if err := oesgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderEventSubscriptionsQuery, *OrderEventSubscriptionsGroupBy](ctx, oesgb.build, oesgb, oesgb.build.inters, v)
}

func (oesgb *OrderEventSubscriptionsGroupBy) sqlScan(ctx context.Context, root *OrderEventSubscriptionsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(oesgb.fns))
	for _, fn := range oesgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*oesgb.flds)+len(oesgb.fns))
		for _, f := range *oesgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*oesgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oesgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OrderEventSubscriptionsSelect is the builder for selecting fields of OrderEventSubscriptions entities.
type OrderEventSubscriptionsSelect struct {
	*OrderEventSubscriptionsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (oess *OrderEventSubscriptionsSelect) Aggregate(fns ...AggregateFunc) *OrderEventSubscriptionsSelect {
	oess.fns = append(oess.fns, fns...)
	return oess
}

// Scan applies the selector query and scans the result into the given value.
func (oess *OrderEventSubscriptionsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oess.ctx, ent.OpQuerySelect)
	if err := oess.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderEventSubscriptionsQuery, *OrderEventSubscriptionsSelect](ctx, oess.OrderEventSubscriptionsQuery, oess, oess.inters, v)
}

func (oess *OrderEventSubscriptionsSelect) sqlScan(ctx context.Context, root *OrderEventSubscriptionsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(oess.fns))
	for _, fn := range oess.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*oess.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oess.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
