// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"system/biz/dal/db/ent/file"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 文件表
type File struct {
	config `json:"-"`
	// ID of the ent.
	// primary key
	ID int64 `json:"id,omitempty"`
	// created time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// last update time
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// last delete  1:已删除 0:未删除
	Delete int64 `json:"delete,omitempty"`
	// created
	CreatedID int64 `json:"created_id,omitempty"`
	// 存储桶名称
	BucketName *string `json:"bucket_name,omitempty"`
	// 文件目录
	FileDirectory *string `json:"file_directory,omitempty"`
	// 文件Guid
	FileGUID *string `json:"file_guid,omitempty"`
	// 保存文件名
	SaveFileName *string `json:"save_file_name,omitempty"`
	// 文件名
	FileName *string `json:"file_name,omitempty"`
	// 文件扩展名
	Extension *string `json:"extension,omitempty"`
	// 文件字节长度
	Size *uint64 `json:"size,omitempty"`
	// 文件大小格式化
	SizeFormat *string `json:"size_format,omitempty"`
	// 链接地址
	LinkURL *string `json:"link_url,omitempty"`
	// md5码，防止上传重复文件
	Md5          *string `json:"md5,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*File) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case file.FieldID, file.FieldDelete, file.FieldCreatedID, file.FieldSize:
			values[i] = new(sql.NullInt64)
		case file.FieldBucketName, file.FieldFileDirectory, file.FieldFileGUID, file.FieldSaveFileName, file.FieldFileName, file.FieldExtension, file.FieldSizeFormat, file.FieldLinkURL, file.FieldMd5:
			values[i] = new(sql.NullString)
		case file.FieldCreatedAt, file.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the File fields.
func (_m *File) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case file.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case file.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case file.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case file.FieldDelete:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delete", values[i])
			} else if value.Valid {
				_m.Delete = value.Int64
			}
		case file.FieldCreatedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_id", values[i])
			} else if value.Valid {
				_m.CreatedID = value.Int64
			}
		case file.FieldBucketName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bucket_name", values[i])
			} else if value.Valid {
				_m.BucketName = new(string)
				*_m.BucketName = value.String
			}
		case file.FieldFileDirectory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_directory", values[i])
			} else if value.Valid {
				_m.FileDirectory = new(string)
				*_m.FileDirectory = value.String
			}
		case file.FieldFileGUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_guid", values[i])
			} else if value.Valid {
				_m.FileGUID = new(string)
				*_m.FileGUID = value.String
			}
		case file.FieldSaveFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field save_file_name", values[i])
			} else if value.Valid {
				_m.SaveFileName = new(string)
				*_m.SaveFileName = value.String
			}
		case file.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				_m.FileName = new(string)
				*_m.FileName = value.String
			}
		case file.FieldExtension:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extension", values[i])
			} else if value.Valid {
				_m.Extension = new(string)
				*_m.Extension = value.String
			}
		case file.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = new(uint64)
				*_m.Size = uint64(value.Int64)
			}
		case file.FieldSizeFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field size_format", values[i])
			} else if value.Valid {
				_m.SizeFormat = new(string)
				*_m.SizeFormat = value.String
			}
		case file.FieldLinkURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link_url", values[i])
			} else if value.Valid {
				_m.LinkURL = new(string)
				*_m.LinkURL = value.String
			}
		case file.FieldMd5:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field md5", values[i])
			} else if value.Valid {
				_m.Md5 = new(string)
				*_m.Md5 = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the File.
// This includes values selected through modifiers, order, etc.
func (_m *File) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this File.
// Note that you need to call File.Unwrap() before calling this method if this File
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *File) Update() *FileUpdateOne {
	return NewFileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the File entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *File) Unwrap() *File {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: File is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *File) String() string {
	var builder strings.Builder
	builder.WriteString("File(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("delete=")
	builder.WriteString(fmt.Sprintf("%v", _m.Delete))
	builder.WriteString(", ")
	builder.WriteString("created_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedID))
	builder.WriteString(", ")
	if v := _m.BucketName; v != nil {
		builder.WriteString("bucket_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FileDirectory; v != nil {
		builder.WriteString("file_directory=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FileGUID; v != nil {
		builder.WriteString("file_guid=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SaveFileName; v != nil {
		builder.WriteString("save_file_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FileName; v != nil {
		builder.WriteString("file_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Extension; v != nil {
		builder.WriteString("extension=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Size; v != nil {
		builder.WriteString("size=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SizeFormat; v != nil {
		builder.WriteString("size_format=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LinkURL; v != nil {
		builder.WriteString("link_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Md5; v != nil {
		builder.WriteString("md5=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Files is a parsable slice of File.
type Files []*File
