// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"crm/biz/dal/db/ent/followuprecord"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FollowUpRecordCreate is the builder for creating a FollowUpRecord entity.
type FollowUpRecordCreate struct {
	config
	mutation *FollowUpRecordMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *FollowUpRecordCreate) SetCreatedAt(v time.Time) *FollowUpRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FollowUpRecordCreate) SetNillableCreatedAt(v *time.Time) *FollowUpRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FollowUpRecordCreate) SetUpdatedAt(v time.Time) *FollowUpRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FollowUpRecordCreate) SetNillableUpdatedAt(v *time.Time) *FollowUpRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDelete sets the "delete" field.
func (_c *FollowUpRecordCreate) SetDelete(v int64) *FollowUpRecordCreate {
	_c.mutation.SetDelete(v)
	return _c
}

// SetNillableDelete sets the "delete" field if the given value is not nil.
func (_c *FollowUpRecordCreate) SetNillableDelete(v *int64) *FollowUpRecordCreate {
	if v != nil {
		_c.SetDelete(*v)
	}
	return _c
}

// SetCreatedID sets the "created_id" field.
func (_c *FollowUpRecordCreate) SetCreatedID(v int64) *FollowUpRecordCreate {
	_c.mutation.SetCreatedID(v)
	return _c
}

// SetNillableCreatedID sets the "created_id" field if the given value is not nil.
func (_c *FollowUpRecordCreate) SetNillableCreatedID(v *int64) *FollowUpRecordCreate {
	if v != nil {
		_c.SetCreatedID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *FollowUpRecordCreate) SetStatus(v int64) *FollowUpRecordCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *FollowUpRecordCreate) SetNillableStatus(v *int64) *FollowUpRecordCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *FollowUpRecordCreate) SetContent(v string) *FollowUpRecordCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *FollowUpRecordCreate) SetNillableContent(v *string) *FollowUpRecordCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetFollowUpID sets the "follow_up_id" field.
func (_c *FollowUpRecordCreate) SetFollowUpID(v int64) *FollowUpRecordCreate {
	_c.mutation.SetFollowUpID(v)
	return _c
}

// SetNillableFollowUpID sets the "follow_up_id" field if the given value is not nil.
func (_c *FollowUpRecordCreate) SetNillableFollowUpID(v *int64) *FollowUpRecordCreate {
	if v != nil {
		_c.SetFollowUpID(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *FollowUpRecordCreate) SetMethod(v int64) *FollowUpRecordCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *FollowUpRecordCreate) SetNillableMethod(v *int64) *FollowUpRecordCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *FollowUpRecordCreate) SetUserID(v int64) *FollowUpRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *FollowUpRecordCreate) SetNillableUserID(v *int64) *FollowUpRecordCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetDivision sets the "division" field.
func (_c *FollowUpRecordCreate) SetDivision(v int64) *FollowUpRecordCreate {
	_c.mutation.SetDivision(v)
	return _c
}

// SetNillableDivision sets the "division" field if the given value is not nil.
func (_c *FollowUpRecordCreate) SetNillableDivision(v *int64) *FollowUpRecordCreate {
	if v != nil {
		_c.SetDivision(*v)
	}
	return _c
}

// SetOpportunitiesID sets the "opportunities_id" field.
func (_c *FollowUpRecordCreate) SetOpportunitiesID(v int64) *FollowUpRecordCreate {
	_c.mutation.SetOpportunitiesID(v)
	return _c
}

// SetNillableOpportunitiesID sets the "opportunities_id" field if the given value is not nil.
func (_c *FollowUpRecordCreate) SetNillableOpportunitiesID(v *int64) *FollowUpRecordCreate {
	if v != nil {
		_c.SetOpportunitiesID(*v)
	}
	return _c
}

// SetRecord sets the "record" field.
func (_c *FollowUpRecordCreate) SetRecord(v string) *FollowUpRecordCreate {
	_c.mutation.SetRecord(v)
	return _c
}

// SetNillableRecord sets the "record" field if the given value is not nil.
func (_c *FollowUpRecordCreate) SetNillableRecord(v *string) *FollowUpRecordCreate {
	if v != nil {
		_c.SetRecord(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FollowUpRecordCreate) SetID(v int64) *FollowUpRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the FollowUpRecordMutation object of the builder.
func (_c *FollowUpRecordCreate) Mutation() *FollowUpRecordMutation {
	return _c.mutation
}

// Save creates the FollowUpRecord in the database.
func (_c *FollowUpRecordCreate) Save(ctx context.Context) (*FollowUpRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FollowUpRecordCreate) SaveX(ctx context.Context) *FollowUpRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FollowUpRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FollowUpRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FollowUpRecordCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := followuprecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := followuprecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Delete(); !ok {
		v := followuprecord.DefaultDelete
		_c.mutation.SetDelete(v)
	}
	if _, ok := _c.mutation.CreatedID(); !ok {
		v := followuprecord.DefaultCreatedID
		_c.mutation.SetCreatedID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := followuprecord.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FollowUpRecordCreate) check() error {
	return nil
}

func (_c *FollowUpRecordCreate) sqlSave(ctx context.Context) (*FollowUpRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FollowUpRecordCreate) createSpec() (*FollowUpRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &FollowUpRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(followuprecord.Table, sqlgraph.NewFieldSpec(followuprecord.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(followuprecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(followuprecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Delete(); ok {
		_spec.SetField(followuprecord.FieldDelete, field.TypeInt64, value)
		_node.Delete = value
	}
	if value, ok := _c.mutation.CreatedID(); ok {
		_spec.SetField(followuprecord.FieldCreatedID, field.TypeInt64, value)
		_node.CreatedID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(followuprecord.FieldStatus, field.TypeInt64, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(followuprecord.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.FollowUpID(); ok {
		_spec.SetField(followuprecord.FieldFollowUpID, field.TypeInt64, value)
		_node.FollowUpID = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(followuprecord.FieldMethod, field.TypeInt64, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(followuprecord.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Division(); ok {
		_spec.SetField(followuprecord.FieldDivision, field.TypeInt64, value)
		_node.Division = value
	}
	if value, ok := _c.mutation.OpportunitiesID(); ok {
		_spec.SetField(followuprecord.FieldOpportunitiesID, field.TypeInt64, value)
		_node.OpportunitiesID = value
	}
	if value, ok := _c.mutation.Record(); ok {
		_spec.SetField(followuprecord.FieldRecord, field.TypeString, value)
		_node.Record = value
	}
	return _node, _spec
}

// FollowUpRecordCreateBulk is the builder for creating many FollowUpRecord entities in bulk.
type FollowUpRecordCreateBulk struct {
	config
	err      error
	builders []*FollowUpRecordCreate
}

// Save creates the FollowUpRecord entities in the database.
func (_c *FollowUpRecordCreateBulk) Save(ctx context.Context) ([]*FollowUpRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FollowUpRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FollowUpRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FollowUpRecordCreateBulk) SaveX(ctx context.Context) []*FollowUpRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FollowUpRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FollowUpRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
