// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"message/biz/dal/db/ent/messagessentrecords"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MessagesSentRecordsCreate is the builder for creating a MessagesSentRecords entity.
type MessagesSentRecordsCreate struct {
	config
	mutation *MessagesSentRecordsMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *MessagesSentRecordsCreate) SetCreatedAt(v time.Time) *MessagesSentRecordsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MessagesSentRecordsCreate) SetNillableCreatedAt(v *time.Time) *MessagesSentRecordsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MessagesSentRecordsCreate) SetUpdatedAt(v time.Time) *MessagesSentRecordsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MessagesSentRecordsCreate) SetNillableUpdatedAt(v *time.Time) *MessagesSentRecordsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDelete sets the "delete" field.
func (_c *MessagesSentRecordsCreate) SetDelete(v int64) *MessagesSentRecordsCreate {
	_c.mutation.SetDelete(v)
	return _c
}

// SetNillableDelete sets the "delete" field if the given value is not nil.
func (_c *MessagesSentRecordsCreate) SetNillableDelete(v *int64) *MessagesSentRecordsCreate {
	if v != nil {
		_c.SetDelete(*v)
	}
	return _c
}

// SetCreatedID sets the "created_id" field.
func (_c *MessagesSentRecordsCreate) SetCreatedID(v int64) *MessagesSentRecordsCreate {
	_c.mutation.SetCreatedID(v)
	return _c
}

// SetNillableCreatedID sets the "created_id" field if the given value is not nil.
func (_c *MessagesSentRecordsCreate) SetNillableCreatedID(v *int64) *MessagesSentRecordsCreate {
	if v != nil {
		_c.SetCreatedID(*v)
	}
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *MessagesSentRecordsCreate) SetMessageID(v int64) *MessagesSentRecordsCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_c *MessagesSentRecordsCreate) SetNillableMessageID(v *int64) *MessagesSentRecordsCreate {
	if v != nil {
		_c.SetMessageID(*v)
	}
	return _c
}

// SetToUserID sets the "to_user_id" field.
func (_c *MessagesSentRecordsCreate) SetToUserID(v int64) *MessagesSentRecordsCreate {
	_c.mutation.SetToUserID(v)
	return _c
}

// SetNillableToUserID sets the "to_user_id" field if the given value is not nil.
func (_c *MessagesSentRecordsCreate) SetNillableToUserID(v *int64) *MessagesSentRecordsCreate {
	if v != nil {
		_c.SetToUserID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *MessagesSentRecordsCreate) SetStatus(v messagessentrecords.Status) *MessagesSentRecordsCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MessagesSentRecordsCreate) SetNillableStatus(v *messagessentrecords.Status) *MessagesSentRecordsCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetReceivedAt sets the "received_at" field.
func (_c *MessagesSentRecordsCreate) SetReceivedAt(v time.Time) *MessagesSentRecordsCreate {
	_c.mutation.SetReceivedAt(v)
	return _c
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_c *MessagesSentRecordsCreate) SetNillableReceivedAt(v *time.Time) *MessagesSentRecordsCreate {
	if v != nil {
		_c.SetReceivedAt(*v)
	}
	return _c
}

// SetReadAt sets the "read_at" field.
func (_c *MessagesSentRecordsCreate) SetReadAt(v time.Time) *MessagesSentRecordsCreate {
	_c.mutation.SetReadAt(v)
	return _c
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_c *MessagesSentRecordsCreate) SetNillableReadAt(v *time.Time) *MessagesSentRecordsCreate {
	if v != nil {
		_c.SetReadAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MessagesSentRecordsCreate) SetID(v int64) *MessagesSentRecordsCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the MessagesSentRecordsMutation object of the builder.
func (_c *MessagesSentRecordsCreate) Mutation() *MessagesSentRecordsMutation {
	return _c.mutation
}

// Save creates the MessagesSentRecords in the database.
func (_c *MessagesSentRecordsCreate) Save(ctx context.Context) (*MessagesSentRecords, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MessagesSentRecordsCreate) SaveX(ctx context.Context) *MessagesSentRecords {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessagesSentRecordsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessagesSentRecordsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MessagesSentRecordsCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := messagessentrecords.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := messagessentrecords.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Delete(); !ok {
		v := messagessentrecords.DefaultDelete
		_c.mutation.SetDelete(v)
	}
	if _, ok := _c.mutation.CreatedID(); !ok {
		v := messagessentrecords.DefaultCreatedID
		_c.mutation.SetCreatedID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MessagesSentRecordsCreate) check() error {
	if v, ok := _c.mutation.Status(); ok {
		if err := messagessentrecords.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MessagesSentRecords.status": %w`, err)}
		}
	}
	return nil
}

func (_c *MessagesSentRecordsCreate) sqlSave(ctx context.Context) (*MessagesSentRecords, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MessagesSentRecordsCreate) createSpec() (*MessagesSentRecords, *sqlgraph.CreateSpec) {
	var (
		_node = &MessagesSentRecords{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(messagessentrecords.Table, sqlgraph.NewFieldSpec(messagessentrecords.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(messagessentrecords.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(messagessentrecords.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Delete(); ok {
		_spec.SetField(messagessentrecords.FieldDelete, field.TypeInt64, value)
		_node.Delete = value
	}
	if value, ok := _c.mutation.CreatedID(); ok {
		_spec.SetField(messagessentrecords.FieldCreatedID, field.TypeInt64, value)
		_node.CreatedID = value
	}
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(messagessentrecords.FieldMessageID, field.TypeInt64, value)
		_node.MessageID = &value
	}
	if value, ok := _c.mutation.ToUserID(); ok {
		_spec.SetField(messagessentrecords.FieldToUserID, field.TypeInt64, value)
		_node.ToUserID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(messagessentrecords.FieldStatus, field.TypeEnum, value)
		_node.Status = &value
	}
	if value, ok := _c.mutation.ReceivedAt(); ok {
		_spec.SetField(messagessentrecords.FieldReceivedAt, field.TypeTime, value)
		_node.ReceivedAt = &value
	}
	if value, ok := _c.mutation.ReadAt(); ok {
		_spec.SetField(messagessentrecords.FieldReadAt, field.TypeTime, value)
		_node.ReadAt = &value
	}
	return _node, _spec
}

// MessagesSentRecordsCreateBulk is the builder for creating many MessagesSentRecords entities in bulk.
type MessagesSentRecordsCreateBulk struct {
	config
	err      error
	builders []*MessagesSentRecordsCreate
}

// Save creates the MessagesSentRecords entities in the database.
func (_c *MessagesSentRecordsCreateBulk) Save(ctx context.Context) ([]*MessagesSentRecords, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MessagesSentRecords, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessagesSentRecordsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MessagesSentRecordsCreateBulk) SaveX(ctx context.Context) []*MessagesSentRecords {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessagesSentRecordsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessagesSentRecordsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
