// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Member is the predicate function for member builders.
type Member func(*sql.Selector)

// MemberContract is the predicate function for membercontract builders.
type MemberContract func(*sql.Selector)

// MemberContractContent is the predicate function for membercontractcontent builders.
type MemberContractContent func(*sql.Selector)

// MemberNote is the predicate function for membernote builders.
type MemberNote func(*sql.Selector)

// MemberProduct is the predicate function for memberproduct builders.
type MemberProduct func(*sql.Selector)

// MemberProductProperty is the predicate function for memberproductproperty builders.
type MemberProductProperty func(*sql.Selector)

// MemberProfile is the predicate function for memberprofile builders.
type MemberProfile func(*sql.Selector)

// MemberTag is the predicate function for membertag builders.
type MemberTag func(*sql.Selector)
